# This file was generated by GoReleaser. DO NOT EDIT.
cask "pipe2" do
  version "0.5.3"

  on_macos do
    on_arm do
      sha256 "45fbb707cbd636d626850bd686680c3e04ef6b88834cd37e7b3490292abf2d0b"
      url "https://github.com/pipe2-ai/pipe2-cli/releases/download/v#{version}/pipe2_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "e1752ee2c4cd1fda96474385dbdbfb10434df58afe463424a71e1b7563ba8446"
      url "https://github.com/pipe2-ai/pipe2-cli/releases/download/v#{version}/pipe2_darwin_x86_64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "c2904d0de9422f0f370654a01784fd387f13af797118ba5fcb187cf741fcfcb6"
      url "https://github.com/pipe2-ai/pipe2-cli/releases/download/v#{version}/pipe2_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "def411a7c9e12a96aaeee0247259c16187df38d8971a7e91915f405098f57b91"
      url "https://github.com/pipe2-ai/pipe2-cli/releases/download/v#{version}/pipe2_linux_x86_64.tar.gz"
    end
  end

  name "pipe2"
  desc "Pipe2.ai CLI — agent-native command line for pipelines, runs, assets, and credits."
  homepage "https://pipe2.ai"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "pipe2"

  postflight do
    if OS.mac?
      system "/usr/bin/xattr", "-dr", "com.apple.quarantine", "#{staged_path}/pipe2"
    end
  end

  # No zap stanza required
end
