# This file was generated by GoReleaser. DO NOT EDIT.
cask "pipe2" do
  version "0.3.0"

  on_macos do
    on_intel do
      sha256 "1b17a98e949752b3103b12a7d8ec563c250f05dd70c26d7914a6ac0329a02133"
      url "https://github.com/pipe2-ai/pipe2-cli/releases/download/v#{version}/pipe2_darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "028a2544939526be5ed9cae09bfcd526d0367b7502e84f26df3070f693888091"
      url "https://github.com/pipe2-ai/pipe2-cli/releases/download/v#{version}/pipe2_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "d3427c19577868c15b308717dd8695f700cd273b125a63f13db13713fb1db2ee"
      url "https://github.com/pipe2-ai/pipe2-cli/releases/download/v#{version}/pipe2_linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "75a284e7b47dba992c1ba817beaadb0a57b0c8d66d8a7a0ada6e9ebca273ebf4"
      url "https://github.com/pipe2-ai/pipe2-cli/releases/download/v#{version}/pipe2_linux_arm64.tar.gz"
    end
  end

  name "pipe2"
  desc "Pipe2.ai CLI — agent-native command line for pipelines, runs, assets, and credits."
  homepage "https://pipe2.ai"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "pipe2"

  postflight do
    if OS.mac?
      system "/usr/bin/xattr", "-dr", "com.apple.quarantine", "#{staged_path}/pipe2"
    end
  end

  # No zap stanza required

end
