# This file was generated by GoReleaser. DO NOT EDIT.
cask "pipe2" do
  version "0.5.2"

  on_macos do
    on_intel do
      sha256 "2def447f47c4bd9d2fb8431bded0a4e36aee831f7692bf5c0e08e614ff420038"
      url "https://github.com/pipe2-ai/pipe2-cli/releases/download/v#{version}/pipe2_darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "dbe57a39a24aa31a0bf13fb286b3bcc0a2b10949906167d78a11ba05da5af94b"
      url "https://github.com/pipe2-ai/pipe2-cli/releases/download/v#{version}/pipe2_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "e511adf2b9b46de6e9983badecc13e99dd2410c6771a780d56760ae17f986581"
      url "https://github.com/pipe2-ai/pipe2-cli/releases/download/v#{version}/pipe2_linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "d954d0dd36e5c00f678a04643a9051cf1ac130d5c9c5c404c8b47d7700f251f9"
      url "https://github.com/pipe2-ai/pipe2-cli/releases/download/v#{version}/pipe2_linux_arm64.tar.gz"
    end
  end

  name "pipe2"
  desc "Pipe2.ai CLI — agent-native command line for pipelines, runs, assets, and credits."
  homepage "https://pipe2.ai"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "pipe2"

  postflight do
    if OS.mac?
      system "/usr/bin/xattr", "-dr", "com.apple.quarantine", "#{staged_path}/pipe2"
    end
  end

  # No zap stanza required

end
